# Change these first
owner: iqfareez # Your GitHub organization or username, where this repository lives
repo: iium-services-status # The name of this repository

sites:
  - name: i-Ma'luum Student Portal
    url: https://imaluum.iium.edu.my
  - name: iTa'LeEM Cloud
    url: https://italeemc.iium.edu.my
  - name: Prereg - Online Course Registration Portal
    url: https://prereg1.iium.edu.my

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /iium-services-status
  logoUrl: https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/International_Islamic_University_Malaysia_logo.svg/1200px-International_Islamic_University_Malaysia_logo.svg.png
  name: IIUM Services Status
  introTitle: "**Orait** ke tuu 👀"
  introMessage: This website is **not affiliated** with IIUM Official. Do reach [them](mailto:servicedesk@iium.edu.my) for help & support. Get notified via [Telegram](http://t.me/iiumstatusbot) now!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/8 * * * *" # every 8 minutes
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
